# Application name
spring.application.name=collateral-tracker

# Server configuration
server.port=8080

# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=collateral-tracker
