# Application name
spring.application.name=collateral-tracker

# Server configuration
server.port=8080

# MongoDB Atlas configuration
spring.data.mongodb.uri=mongodb+srv://Cluster00931:SERBaXBXZmRn@cluster00931.llte3wj.mongodb.net/collateral-tracker
spring.data.mongodb.database=collateral-tracker
